main: net.juligames.core.paper.PaperCorePlugin
version: 0.0.1 - Micheal
name: PaperCore
author: Ture Bentzin
commands:
  message:
    description: test message core
    usage: /message messageKey
  locale:
    description: get your own locale
    usage: /locale (Only for Players)
  replacetest:
    description: test replacers
    usage: /replacetest args
  bctest:
    description: test broadcast
    usage: /bctest key